language: java

jdk: openjdk8

env: DISPLAY=:99.0

services:
   - docker

# skip installation step
install: true

cache:
   directories:
      - $HOME/.m2

before_script:
   - sh -e /etc/init.d/xvfb start

script:
   - mvn -f com.examples.school/pom.xml clean verify
